kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: blinkt-animation-controller-client
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: blinkt-animation-controller-client
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      nodeSelector:
        blinktClient: "true"
      containers:
      - name: blinkt-animation-controller-client
        image: ngpitt/blinkt-animation-controller-client:v1
        args:
        - -server=blinkt-animation-controller-server.kube-system:8888
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /sys
          name: sys-tree
      volumes:
      - name: sys-tree
        hostPath:
          path: /sys
